### ISSUE TITLE
Boot loop when using adaptive brightness

### ISSUE THREAD

**Issue by casef** [Pulkit077/device_xiaomi_sweet#1]
Hi, several people on XDA have noticed an issue where as the phone boots up, the PIN screen is briefly shown, only for the device to show the boot animation again, show the PIN screen...and rince and repeat (seemingly) endlessly.

I installed the ROM yesterday and was eventually met with the same issue, so I tried looking a bit more into what might be causing it and it seems that there's some kind of issue with adaptive brightness, at least when the device boots (I don't seem to have any issues with it when I manage to boot the system fully). In particular, I've noticed this in system log:

`08-14 12:21:57.123  3139  3173 D ColorDisplayService: setUp: currentUser=0
08-14 12:21:57.127  3139  3236 E AppHibernationService: Attempt to call isHibernatingForUser on stopped or nonexistent user 0
08-14 12:21:57.142  3139  3183 I ActivityManager: Start proc 4186:com.google.android.apps.wellbeing/u0a101 for on-hold
08-14 12:21:57.166  3139  3173 D ColorDisplayService: onNightDisplayAutoModeChanged: autoMode=0
08-14 12:21:57.166  3139  3173 I ColorDisplayService: Turning off night display
08-14 12:21:57.166  3139  3173 D ColorDisplayService: Setting bright color reduction level: 50
08-14 12:21:57.167  3139  3218 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: PowerManagerService
08-14 12:21:57.167  3139  3218 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid value: NaN for setting: screen_auto_brightness_adj
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.providers.settings.SettingsProvider.validateSystemSettingValue(SettingsProvider.java:1950)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:1918)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:1840)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:462)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.content.ContentProvider.call(ContentProvider.java:2464)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.content.ContentProvider$Transport.call(ContentProvider.java:512)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:2867)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.provider.Settings$System.putStringForUser(Settings.java:3574)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.provider.Settings$System.putStringForUser(Settings.java:3558)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.provider.Settings$System.putFloatForUser(Settings.java:3859)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.server.display.DisplayPowerController.putAutoBrightnessAdjustmentSetting(DisplayPowerController.java:2138)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.server.display.DisplayPowerController.updatePowerState(DisplayPowerController.java:1285)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.server.display.DisplayPowerController.access$700(DisplayPowerController.java:101)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.server.display.DisplayPowerController$DisplayControllerHandler.handleMessage(DisplayPowerController.java:2467)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.os.Looper.loopOnce(Looper.java:201)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:288)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at android.os.HandlerThread.run(HandlerThread.java:67)
08-14 12:21:57.167  3139  3218 E AndroidRuntime:     at com.android.server.ServiceThread.run(ServiceThread.java:44)`

Based on this, I figured out that if I cover the brightness sensor with my hand or if I put the phone into a darker environment so the screen actually darkens once the PIN screen shows, the loop stops, you can enter PIN and the device then finishes the boot normally. You don't even have to keep covering the sensor as you enter the PIN, as soon as the screen darkens after the PIN screen shows up, you can uncover the sensor and the loop will no longer happen and the adaptive brightness will work fine.

Alternatively, if you disable adaptive brightness in settings, the issue doesn't seem to show up at all.

As part of my troubleshooting, I've tried flashing firmware 13.0.8.0 (as recommended), 13.0.10.0 and the newest 13.0.13.0, and it doesn't seem to have an effect on this, happens with all of them. Please note though that I did not do full reinstall when flashing these firmwares, I just flashed them through Orange Fox 12.1 on already installed ROM, so I'm not sure if that might still be a factor. The ROM was originally installed with 13.0.10.0 as that's the firmware the guy on XDA linking the ROM was using. I can certainly try a complete reinstall if that might help something, but it really seems like the issue manifests for people on any fw.

I can of course also provide more logs or anything needed.

Thank you.

**Comment by Pulkit077** [comment]
Thank you for reporting, The issue was recently reported to me via telegram as well and I've looked into system crashing when rebooting with auto brightness enabled and I've fixed it internally on rom sources side.
There will be an update available soon fixing above mentioned

**Comment by casef** [comment]
Thank you for providing such a great customized Lineage ROM :)

**Comment by Pulkit077** [comment]
This was fixed on 19 Sept LOS 19.1 build on source side
